logging:
  config: classpath:log4j2.xml
  level:
    com:
      example:
        uiplog:
          mapper: debug
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  context-path: /api-log
  port: '5013'
  session:
    timeout: '30'
  tomcat:
    uri-encoding: UTF-8
spring:
  activiti:
    check-process-definitions: false
  redis:
    host: 10.17.0.12
    port: 6379
    pool:
      maxTotal: 1000
      maxIdle: 100
      minIdle: 50
      maxWaitMillis: 10000
      testOnBorrow: true
      testOnReturn: true
      timeBetweenEvictionRunsMillis: 30000
      testWhileIdle: true
      numTestsPerEvictionRun: 50

primaryDB:
  datasource:
    #druid相关配置
    druid:
      driverClassName: org.postgresql.Driver
      password: '123456'
      #      url: jdbc:postgresql://10.0.96.128:5432/advance
      url: jdbc:postgresql://10.17.0.12:5432/szy
      username: postgres
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 200
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。PSCache对支持游标的数据库性能提升巨大，比如说oracle
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
jwt:
  api-token: ZXlKcmFXUWlPaUl3SWl3aWRIbHdJam9pU2xkVUlpd2lZV3huSWpvaVNGTXlOVFlpZlEuZXlKcFlYUWlPakUxTXpVMk1UUTJNREVzSW5OMVlpSTZJbXh2WjJsdUlpd2lhWE56SWpvaVYwVkVVeUlzSW5CaGJHY2lPaUpoWlhNdE1qVTJMV05pWXlJc0luQnJaWGxwWkNJNklqRWlMQ0pxZEdraU9pSjFjMlZ5TVRJek5EWmhZMk52ZFc1MExYTmxjblpwWTJWc2IyZHBiaUlzSW1GMVpDSTZJbUZqWTI5MWJuUXRjMlZ5ZG1salpTSXNJbkJrWVhSaElqb2laREF5WmpRMk16UmxOV0ZrTjJReVltTTBPVGd6WmpJeU5ERmxNak5pWWpsbFpEQmhZMkl3WkRGa1kyWm1aakJoWTJSa1pqVXdaR0ppWldVelpqZGlOMk16TTJSa1l6RmhaR0ZtWTJWaVl6VTJOVFJoWVRReE5qbGpaalpqTjJWaU1UUTBaV1JtTVRSa01XTmlPVFF4TnpKaE9HVXpOekZsTW1RME9URmhPR0lpZlEuTG4wdUMtaG10ejN3U01hakdxUGxocXBQanBnYVpscS1rRVBMVkt1NjdLRQ==
  secret-key: 4OFGE6luXcTtnjLMcQn8JanoSl4i1yfb
  secret-pkey: 01234567890123456789012345678901&0123456789012345,12345678901234567890123456789012&1234567890123456
  active: true
  filter: "account/loginCheck.*$,account/getVerify,account/checkIndex,account/loginCasCheck/.*$,account/wxLogin/.*$,account/ssoLogin,account/scmLogin/.*$,account/getLoginSrc,account/app-ticket,account/loginFromApp/.*$,websocket.*,index.html,doc.html,static.*,images.*,fileAtt.*,img.*,imageRe.*,^.*/export/.*$,^.*/upload/.*$,sysConfig/.*$,favicon.ico,testMq/send,ssoLogin.*,sso.html.*,screen/screenData.*$,rpc,screenConfig/.*$,account/accessTicket,account/loginFromScm/.*$,account/getSysInfo,screen/reload,userForeign/register,comm/getWeather,screen/screenInfo.*$"





